spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb
    driver-class-name: org.postgresql.Driver
    username: batch_user
    password: batch_pass

# Surcharger le fichier via --inputFile=/chemin/vers/fichier au lancement

logging:
  level:
    dev.kore.batch: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
