spring:
  application:
    name: kore-batch-sample
  main:
    web-application-type: none
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never  # Géré par Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb
    driver-class-name: org.postgresql.Driver
    username: batch_user
    password: batch_pass
  jpa:
    hibernate:
      ddl-auto: none

batch:
  partitioning:
    pool-size: 4
    queue-capacity: 50
    grid-size: 4

logging:
  level:
    fr.kore.batch: DEBUG
    org.springframework.batch: INFO
